author = Artur Tarassow
email = atecon@cryptolab.net
version = 0.1
date = 2019-02-25
description = Plotting Library
tags = C12 C52 C53
min-version = 2018a
data-requirement = no-data-ok
public = GPlotFun ecdf_plot
help = GPlotFun.pdf
sample-script = GPlotFun_sample.inp
#data-files = FEPdata.gdt
depends = extra
